{% set name = "fdm" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fdm-{{ version }}.tar.gz
  sha256: 47876c8fe8aea4b374913594938cbcbd065a648d044fe8e287af7f320341ef39

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.10
    - hatch-vcs >=0.3
  run:
    - python >=3.8
    - numpy >=1.16
    - sympy

test:
  imports:
    - fdm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wesselb/fdm
  summary: Compute derivatives with finite-difference methods
  license: MIT
  license_file: LICENCE.txt
  doc_url: https://wesselb.github.io/fdm
  dev_url: https://github.com/wesselb/fdm

extra:
  recipe-maintainers:
    - wesselb
